# Generated by Django 5.2.7 on 2026-08-17 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edairy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='farmer',
        ),
        migrations.RenameField(
            model_name='cow',
            old_name='owner',
            new_name='farmer',
        ),
    ]
