# Generated by Django 5.2.7 on 2026-08-27 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edairy', '0003_rename_owner_farmer_rename_owner_cow_farmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='farmer',
            new_name='farm_manager',
        ),
        migrations.RenameField(
            model_name='cow',
            old_name='farmer',
            new_name='farm_manager',
        ),
        migrations.RemoveField(
            model_name='calf',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='age',
        ),
        migrations.AddField(
            model_name='calf',
            name='date_of_birth',
            field=models.DateField(blank=True, null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='calf',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SICK', 'Sick'), ('SOLD', 'Sold'), ('DEAD', 'Dead')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PREGNANT', 'Pregnant'), ('SICK', 'Sick'), ('DRY', 'Dry'), ('SOLD', 'Sold'), ('DEAD', 'Dead')], default='ACTIVE', max_length=20),
        ),
    ]
