# Generated by Django 5.2.7 on 2025-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edairy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
