# Generated by Django 5.2.7 on 2026-01-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='management',
            managers=[
            ],
        ),
    ]
