# Generated by Django 5.2.7 on 2026-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_management_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
